# -*- coding: utf-8 -*-
"""Wordle latest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GOeoWURrKEDqP98p_H9uWMTM9ktVNaie
"""

import random
import os
from colorama import Fore
import nltk
os.system('cls')
nltk.download('words')
words = nltk.corpus.words.words()
word_list=[]    #Only contains valid five letter words(unique) and target word is picked from this list
os.system('cls')
print("Welcome to Wordle!")
prompt=r'''      _.--._  _.--._
,-=.-":;:;:;\':;:;:;"-._
\\\:;:;:;:;:;\:;:;:;:;:;\
 \\\:;:;:;:;:;\:;:;:;:;:;\
  \\\:;:;:;:;:;\:;:;:;:;:;\
   \\\:;:;:;:;:;\:;::;:;:;:\
    \\\;:;::;:;:;\:;:;:;::;:\
     \\\;;:;:_:--:\:_:--:_;:;\
      \\\_.-"      :      "-._\
       \`_..--""--.;.--""--.._=>
        "'''
rules=r'''1.You have to guess a five letter word.Each letters are unique in the target word
2.Your guess must be a word of length five
3.The word you input must be of five unique letters'''
print(rules)
for word in words:
    if len(word)==5 == len(set(word))==5:
        word_list.append(word.upper())

def func(word_list):
    print(prompt)
    count=0
    target=random.choice(word_list)
    sum=''
    hints=''
    var=True
    word_found=False
    while var:
        sum='' #hints without color
        hints='' #hints
        while count<6 and sum!=target: # Changed count<6 to count<=6

            user_input=input(f'Guess {count+1}: ').upper()
            sum2='' #user_input will be stripped of spaces and stored in this variable
            for i in user_input: #striping spaces from user input
                if i!=' ':
                    sum2+=i
            user_input = sum2

            if user_input not in word_list or len(set(user_input))!=5:
                print("Word must contain unique characters.Word length must be five and the word must be real.")
                count-=1
            else:
                for i in range(5): # Added a for loop to compare each letter
                    if user_input[i]==target[i]:
                        hints+= Fore.GREEN + user_input[i] + Fore.RESET
                        sum+=user_input[i]
                    elif user_input[i] not in target:
                        hints+= Fore.RED + user_input[i] + Fore.RESET
                        sum+=user_input[i]
                    else:
                        hints+=Fore.YELLOW + user_input[i] + Fore.RESET
                        sum+=user_input[i]
                else:
                    if target == sum:
                        print(f"Correct.The word is {hints}")
                        var = False
                        word_found = True
                        break
            count+=1
            print(hints)
            hints=''
            sum=''
            if count==6:
                var=False #It would have been same if I used break instead of var=False

    if not word_found:
        print('Target Word:',target)

x='y'
loop=True
while loop:
    if x=='y':

        func(word_list)
        x=input('again? y/n :')
        os.system('cls')
    else:
        input('press enter to exit')
        loop=False